### ISSUE TITLE
Security Vulnerability: Exposure of Helius API Key

### ISSUE THREAD

**Issue by chainsona** [solana-developers/solana_game_preset#2]
Solana Developers,

I have identified a security vulnerability in your codebase that requires immediate attention. I discovered the presence of an unsecured Helius API key within the source code.

To mitigate this issue, we recommend that you take immediate action to address this vulnerability by following these steps:

- Identify and remove all instances of the Helius API key from the codebase. Please find one occurrence in https://github.com/solana-developers/solana_game_preset/blob/main/app/utils/anchor.ts#L11
- Replace the API key with an environment variable that can be set.

Thank you for your attention to this matter.

**Comment by Woody4618** [comment]
Hey, thanks a lot. It's a free api key to show how to load cNFTs. Its there so it works out of the box, but for production the people using the api would need to sign up for a payed plan. I will check if I can maybe use MetaPlexReadApi instead. Thank you for the report.
