### ISSUE TITLE
[suggestion] rename to create-solana-game

### ISSUE THREAD

**Issue by mikemaccana** [solana-developers/solana_game_preset#3]
Right now, other docs refer to this as both 'solana_game_preset' 'Solana game Scaffold'. Renaming the repo (and updating the README) to call this 'create-solana-game' will get more SEO, match the command, be consistent with `create-solna-dapp` and be more memorable. github will set up the redirect for you.

**Comment by Woody4618** [comment]
I don't have the rights to do that. That would be on @jacobcreech i guess.
